logger:
  level: "INFO"
database:
  use: false
  dsn: "postgresql://db_user:super_secret_password_42@localhost:5432/calendardb"
server:
  http:
    address: "localhost:3000"
    log_file: "/tmp/calendar-http-logs.txt"
    timeout: 5s
    idle_timeout: 20s
  grpc:
    port: ":50051"
    log_file: "/tmp/calendar-grpc-logs.txt"
