logger:
  level: "INFO"
database:
  dsn: "postgresql://db_user:super_secret_password_42@localhost:5432/calendardb"
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  routing_key: "evenoti"
  exchange:
    name: "events"
    type: "direct"
    durable: true
    auto_delete: false
    internal: false
    no_wait: false
  queue:
    name: "notifications"
    durable: true
    auto_delete: false
    exclusive: false
    no_wait: false
interval: 24h
